# Docker Compose file for testing
version: "3.4"
services:

  db:
    image: postgres:12.3
    environment:
      POSTGRES_USER: critiquebrainz
      POSTGRES_PASSWORD: critiquebrainz
      POSTGRES_DB: critiquebrainz
    command: postgres -F
    volumes:
      - ./pg_custom:/docker-entrypoint-initdb.d/

  musicbrainz_db:
    image: metabrainz/brainzutils-mb-sample-database:schema-25-2021-04-04.0
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  critiquebrainz_redis:
    image: redis:4.0-alpine

  critiquebrainz:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ..:/code
    depends_on:
      - db
      - musicbrainz_db
      - critiquebrainz_redis
    environment:
      PGPASSWORD: critiquebrainz
